### ISSUE TITLE
Mermaid ```Mermaid syntax

### ISSUE THREAD

**Issue by chris2fr** [MikeCoder/markdown-preview.vim#15]
## Expected Behavior 

With the following, I should see a mermaid diagram:

```mermaid
graph LR
A -> B
B -> C
C -> A
```

## Actual Behavior

The text as follows is apparant

```
\'\'\'mermaid
A->B
B->C
C -> A
\`\`\`
```

## Steps to Reproduce the Problem

  1. Create the above file
  1. <leader> m
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

AlpineLinux in WSL

**Comment by D0n9X1n** [comment]
I found there are two issues in your example snippet.

1. You need use keyword `chart` instead of `mermaid`.
2. You need use `-->` instead of `->`

Here is my test on my computer:

Code:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/3142935/108620289-23bce400-7466-11eb-9cbd-af4e5abb9b33.png">

Result:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/3142935/108620293-2b7c8880-7466-11eb-9be8-f83272113a03.png">

If still not working, can you try to use [TEST.md](https://github.com/D0n9X1n/markdown-preview.vim/blob/master/TEST.md) which should be under the plugin installed folder and test the result?

**Comment by chris2fr** [comment]
The issue was with the ```mermaid call. instead of the ```chart call. Many Markdown syntaxi allow for the ```mermaid syntax.

The other issue is from my Graphviz/Dot days.... Good catch. Thanks.

**Comment by D0n9X1n** [comment]
I see, when I wrote this plugin, there were few markdown syntaxi supported that feature so that I use `chart` to represent this. 

I just submit a commit to support this keyword, you can update and try it.

See https://github.com/D0n9X1n/markdown-preview.vim#for-flowcharts

**Comment by chris2fr** [comment]
All Good for Mermaid.
I would like to test further for Windows compatibility in order to take down the message about discouraging in Windows.
